import React, { useState } from "react";
import Head from "next/head";
import axios from "axios";
import styles from "../styles/Home.module.css";

const Data = (props) => {
  const [data, setData] = useState(props?.data || null);
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [message, setMessage] = useState("");

  const handleSubmit = async (event) => {
    event.preventDefault();

    // Submit the form data to the server using axios
    const response = await axios.post("http://localhost:3001/api/hello", {
      name,
      email,
      message,
    });

    setData(response.data.data);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data && (
          <>
            <h1 className={styles.title}>Name: {data.name}</h1>
            <h1 className={styles.title}>Email: {data.email}</h1>
            <h1 className={styles.title}>Message: {data.message}</h1>
          </>
        )}

        <div>
          <form onSubmit={handleSubmit} className={styles.form_container}>
            <label>
              Name:
              <input
                type="text"
                value={name}
                onChange={(event) => setName(event.target.value)}
              />
            </label>
            <label>
              Email:
              <input
                type="email"
                value={email}
                onChange={(event) => setEmail(event.target.value)}
              />
            </label>
            <label>
              Message:
              <textarea
                value={message}
                onChange={(event) => setMessage(event.target.value)}
              />
            </label>
            <button type="submit">Submit</button>
          </form>
        </div>
      </main>
    </div>
  );
};

export async function getStaticProps() {
  const response = await axios.get("http://localhost:3001/api/hello");
  return { props: response.data };
}

export default Data;
